___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

# Вивести версію та конфігурацію бібліотеки:

In [2]:
# Версія бібліотеки numpy
print("Версія numpy:", np.__version__)

# Конфігурація бібліотеки numpy
print("Конфігурація numpy:")
np.show_config()

Версія numpy: 1.23.5
Конфігурація numpy:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c

Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
v = np.ones(10)

print(v)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
v = np.arange(0, 11)

print(v)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
v = np.zeros((5, 5))

print(v)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [6]:
v = np.random.randint(low=0, high=100, size=20)

nonzero_indices = np.nonzero(v)

print(v)
print(nonzero_indices)

[ 0 82 16 38 32 27 35 42 46 80 93 63 87 61 88 53 54 45 58 58]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [7]:
median = np.median(v)
mean = np.mean(v)
std = np.std(v)

print("Медіана: ", median)
print("Середнє значення: ", mean)
print("Відхилення: ", std)

Медіана:  53.5
Середнє значення:  52.9
Відхилення:  24.33495428391021


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [10]:
m1 = np.random.randint(0, 30, size=(4, 2))
m2 = np.random.randint(0, 30, size=(2, 2))

m = np.dot(m1, m2)
print(m)

[[735 786]
 [595 626]
 [605 652]
 [715 752]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [11]:
m_list = np.ravel(m)
print("Матриця у вигляді списку: ", m_list)

m_max = np.max(m_list)
m_min = np.min(m_list)
print("Мінімальне та максимальне: ", m_max, "    ", m_min)

m_list[m_list == m_max] = 0
print("Змінена матриця у вигляді списку: ", m_list)

Матриця у вигляді списку:  [735 786 595 626 605 652 715 752]
Мінімальне та максимальне:  786      595
Змінена матриця у вигляді списку:  [735   0 595 626 605 652 715 752]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [18]:
#Функція np.corrcoef шукає кореляції між рядками матриці, тобто між зразками. 
#Кожен рядок матриці вважається окремим зразком, 
#а кожний стовпець - окремою ознакою цих зразків. 
#Тому функція обчислює кореляції між зразками, а не між ознаками.


corr = np.corrcoef(m)


corr

array([[ 1., -1., -1., -1.],
 [-1., 1., 1., 1.],
 [-1., 1., 1., 1.],
 [-1., 1., 1., 1.]])

In [19]:
print(corr[0])

[ 1. -1. -1. -1.]


Дано матрицю. Знайти ранг матриці:

In [20]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

rank = np.linalg.matrix_rank(a)
print(rank)

3


Знайти визначник матриці:

In [22]:
det = np.linalg.det(a)
print(round(det, 1))

440.0


Знайти власні значення та власні вектори матриці: 

In [23]:
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Власні значення:")
print(eigenvalues)
print("Власні вектори:")
print(eigenvectors)

Власні значення:
[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні вектори:
[[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [49]:
a = np.random.randint(0,10,50)

print(a)
print(np.bincount(a).argmax())


[1 3 5 0 4 6 5 9 5 0 6 6 5 0 8 4 2 0 3 7 7 4 1 9 0 0 6 8 9 7 3 9 5 6 8 0 3
 6 9 2 8 4 7 9 4 6 8 2 0 8]
0


Виведіть лише парні числа, що діляться на 5:

In [ ]:
a = np.random.randint(0,10,50)

In [50]:
print(a)
print(a[a == 0])

[1 3 5 0 4 6 5 9 5 0 6 6 5 0 8 4 2 0 3 7 7 4 1 9 0 0 6 8 9 7 3 9 5 6 8 0 3
 6 9 2 8 4 7 9 4 6 8 2 0 8]
[0 0 0 0 0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [51]:
first_eq = np.array([[2, 5], [1, -10]])
second_eq = np.array([1, 3])

result = np.linalg.solve(first_eq, second_eq)
print("x, y:")
print(result)

x, y:
[ 1.  -0.2]
